apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: think-twice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: think-twice-secrets
                  key: AUTH_MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: think-twice-secrets
                  key: JWT_SECRET