apiVersion: apps/v1
kind: Deployment
metadata:
  name: org-service
  namespace: think-twice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org-service
  template:
    metadata:
      labels:
        app: org-service
    spec:
      containers:
        - name: org-service
          image: org-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: think-twice-secrets
                  key: ORG_MONGODB_URI
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: think-twice-secrets
                  key: REDIS_URL