// services/decision-service/utils/eventEmitter.js
import { redisClient } from './redisClient.js';

// Stream names
const STREAM_NAMES = {
  DECISION_CREATED: 'decision:created',
  DECISION_UPDATED: 'decision:updated',
  DECISION_RESOLVED: 'decision:resolved',
};

/**
 * Emit an event to Redis Streams
 * @param {string} streamName - Name of the stream (e.g., 'decision:created')
 * @param {object} eventData - Event payload
 * @returns {Promise<string>} - Event ID generated by Redis
 */
export const emitEvent = async (streamName, eventData) => {
  try {
    const eventId = await redisClient.xAdd(streamName, '*', {
      timestamp: new Date().toISOString(),
      ...eventData,
      // Convert objects to JSON strings for Redis storage
      ...(eventData.decision && { decision: JSON.stringify(eventData.decision) }),
      ...(eventData.user && { user: JSON.stringify(eventData.user) }),
    });
    
    console.log(`📤 Event emitted to "${streamName}":`, eventId);
    return eventId;
  } catch (error) {
    console.error(`❌ Failed to emit event to "${streamName}":`, error.message);
    throw error;
  }
};

/**
 * Create a consumer group for a stream
 * @param {string} streamName - Name of the stream
 * @param {string} groupName - Name of the consumer group
 * @param {string} startId - Starting message ID ('$' for new messages, '0' for all)
 */
export const createConsumerGroup = async (streamName, groupName, startId = '0') => {
  try {
    // First, ensure stream has at least one message (so the group can be created)
    await redisClient.xGroupCreate(streamName, groupName, startId, {
      MKSTREAM: true, // Create stream if it doesn't exist
    });
    console.log(`✅ Consumer group "${groupName}" created for stream "${streamName}"`);
  } catch (error) {
    if (error.message.includes('BUSYGROUP')) {
      console.log(`ℹ️  Consumer group "${groupName}" already exists`);
    } else {
      console.error(`❌ Failed to create consumer group "${groupName}":`, error.message);
      throw error;
    }
  }
};

/**
 * Read pending messages from a consumer group
 * @param {string} streamName - Name of the stream
 * @param {string} groupName - Name of the consumer group
 * @param {string} consumerName - Name of the consumer
 * @param {number} count - Number of messages to read
 */
export const readPendingMessages = async (streamName, groupName, consumerName, count = 10) => {
  try {
    const messages = await redisClient.xReadGroup(
      { key: streamName, group: groupName, consumer: consumerName },
      { count, block: 0 } // block: 0 means wait indefinitely
    );
    return messages;
  } catch (error) {
    console.error(`❌ Failed to read messages from "${streamName}":`, error.message);
    throw error;
  }
};

/**
 * Acknowledge a processed message
 * @param {string} streamName - Name of the stream
 * @param {string} groupName - Name of the consumer group
 * @param {string} messageId - ID of the message to acknowledge
 */
export const acknowledgeMessage = async (streamName, groupName, messageId) => {
  try {
    await redisClient.xAck(streamName, groupName, messageId);
    console.log(`✅ Message acknowledged:`, messageId);
  } catch (error) {
    console.error(`❌ Failed to acknowledge message:`, error.message);
    throw error;
  }
};

export { STREAM_NAMES };
